
"use client";

import { useFormState, useFormStatus } from "react-dom";
import { Bot, Loader2, Music, Ship } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { getShanty } from "./actions";
import { useState, useEffect } from "react";
import type { Vessel } from "@/lib/types";
import { getVessels } from "@/lib/firestore";
import { Skeleton } from "@/components/ui/skeleton";
import Markdown from 'react-markdown';


function SubmitButton() {
  const { pending } = useFormStatus();
  return (
    <Button type="submit" disabled={pending} className="w-full">
      {pending ? (
        <>
          <Loader2 className="mr-2 h-4 w-4 animate-spin" />
          Composing Shanty...
        </>
      ) : (
        <>
          <Bot className="mr-2 h-4 w-4" />
          Generate Shanty
        </>
      )}
    </Button>
  );
}

export default function ShantyAiPage() {
  const initialState = { data: null, error: null, message: "" };
  const [state, formAction] = useFormState(getShanty, initialState);
  const [vessels, setVessels] = useState<Vessel[]>([]);
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    async function fetchData() {
      try {
        setIsLoading(true);
        const vesselData = await getVessels();
        setVessels(vesselData);
      } catch (error) {
        console.error("Failed to fetch vessels for AI form", error);
      } finally {
        setIsLoading(false);
      }
    }
    fetchData();
  }, []);

  return (
    <div className="flex flex-col gap-4">
      <div className="flex items-center gap-4">
        <h1 className="text-2xl font-semibold md:text-3xl">AI Shanty Generator</h1>
      </div>
      <p className="text-muted-foreground">
        Select a vessel and let the AI compose a traditional sea shanty in its honor.
      </p>

      <div className="grid gap-8 md:grid-cols-2 lg:grid-cols-3">
        <Card className="lg:col-span-1">
          <CardHeader>
            <CardTitle>Shanty Parameters</CardTitle>
            <CardDescription>
              Choose a vessel to immortalize in song.
            </CardDescription>
          </CardHeader>
          <CardContent>
            {isLoading ? (
                 <div className="grid gap-6">
                    <div className="grid gap-2">
                        <Skeleton className="h-4 w-16" />
                        <Skeleton className="h-10 w-full" />
                    </div>
                    <Skeleton className="h-10 w-full" />
                </div>
            ) : (
            <form action={formAction} className="grid gap-6">
              <div className="grid gap-2">
                <Label htmlFor="vesselId">Vessel</Label>
                 <Select name="vesselId" required>
                  <SelectTrigger>
                    <SelectValue placeholder="Select a vessel" />
                  </SelectTrigger>
                  <SelectContent>
                    {vessels.map(v => <SelectItem key={v.id} value={v.id}>{v.name}</SelectItem>)}
                  </SelectContent>
                </Select>
              </div>
              <SubmitButton />
            </form>
            )}
          </CardContent>
        </Card>
        
        <div className="lg:col-span-2">
        {state.error && (
          <Alert variant="destructive" className="mb-4">
            <AlertTitle>Error</AlertTitle>
            <AlertDescription>
              There was an error processing your request: {state.error}
            </AlertDescription>
          </Alert>
        )}

        {state.data ? (
          <Card>
              <CardHeader className="flex flex-row items-center gap-4 space-y-0">
                  <Music className="w-8 h-8 text-primary" />
                  <div>
                      <CardTitle>{state.data.title}</CardTitle>
                      <CardDescription>A custom sea shanty generated by MarinaSuite AI</CardDescription>
                  </div>
              </CardHeader>
              <CardContent>
                  <div className="prose prose-sm dark:prose-invert max-w-none text-muted-foreground leading-relaxed whitespace-pre-wrap">
                      <Markdown>{state.data.shanty}</Markdown>
                  </div>
              </CardContent>
          </Card>
        ) : (
          <div className="flex flex-col items-center justify-center h-full rounded-lg border border-dashed p-8 text-center">
              <Bot className="w-16 h-16 text-muted-foreground/50" />
              <h3 className="mt-4 text-lg font-semibold">Awaiting Inspiration</h3>
              <p className="mt-2 text-sm text-muted-foreground">
                  Your AI-generated sea shanty will appear here.
              </p>
          </div>
        )}
        </div>
      </div>
    </div>
  );
}
