name: Sync AI Studio from Google Drive

on:
  schedule:
    - cron: '0 */6 * * *'  # every 6 hours
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install --upgrade google-api-python-client google-auth google-auth-httplib2 google-auth-oauthlib

      - name: Download ZIP from Google Drive
        env:
          GDRIVE_SERVICE_KEY: ${{ secrets.GDRIVE_MARINASUITE_SERVICE_KEY }}
        run: |
          echo "$GDRIVE_SERVICE_KEY" > service_account.json

          FILE_ID=$(python3 -c "
import json
from google.oauth2 import service_account
from googleapiclient.discovery import build

creds = service_account.Credentials.from_service_account_file('service_account.json')
drive = build('drive', 'v3', credentials=creds)

results = drive.files().list(q=\"name='quanzab.zip' and trashed=false\", spaces='drive', fields='files(id, name)').execute()
file = results.get('files', [])[0]
print(file['id'])
")

          curl -X GET -L \
          -H \"Authorization: Bearer $(gcloud auth application-default print-access-token)\" \
          \"https://www.googleapis.com/drive/v3/files/$FILE_ID?alt=media\" \
          --output quanzab.zip

      - name: Unzip project
        run: |
          rm -rf project && mkdir project
          unzip -o quanzab.zip -d project
          cp -r project/* ./

      - name: Commit and Push
        run: |
          git config user.name "aistudio-bot"
          git config user.email "bot@aistudio.com"
          git add .
          git commit -m "Auto-sync from Google Drive [$(date)]" || echo "No changes to commit"
          git push
