name: GDrive Sync

on:
  schedule:
    - cron: '0 */6 * * *'  # Runs every 6 hours
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install google-api-python-client google-auth-httplib2 google-auth-oauthlib

      - name: Write Google Service Account Credentials
        env:
          GDRIVE_MARINASUITE_SERVICE_KEY: ${{ secrets.GDRIVE_MARINASUITE_SERVICE_KEY }}
        run: |
          echo "$GDRIVE_MARINASUITE_SERVICE_KEY" > service_account.json

      - name: Download Quanzab ERP Lite.zip from Google Drive
        run: |
          cat <<EOF > download_gdrive.py
import json
from google.oauth2 import service_account
from googleapiclient.discovery import build
import io
from googleapiclient.http import MediaIoBaseDownload

creds = service_account.Credentials.from_service_account_file('service_account.json')
drive = build('drive', 'v3', credentials=creds)

results = drive.files().list(q="name='Quanzab ERP Lite.zip' and trashed=false", spaces='drive', fields='files(id, name)').execute()
files = results.get('files', [])

if not files:
    raise Exception("Quanzab ERP Lite.zip not found in Google Drive")

file_id = files[0]['id']
request = drive.files().get_media(fileId=file_id)
fh = io.FileIO('quanzab.zip', 'wb')
downloader = MediaIoBaseDownload(fh, request)

done = False
while not done:
    status, done = downloader.next_chunk()
    print(f"Download progress: {int(status.progress() * 100)}%")
EOF
          python3 download_gdrive.py

      - name: Unzip and copy files
        run: |
          rm -rf project
          unzip -o quanzab.zip -d project
          cp -r project/* ./

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git diff --staged --quiet || git commit -m "Sync from Google Drive"
          git push
