name: Sync AI Studio from Google Drive

on:
  schedule:
    - cron: '0 */6 * * *'  # every 6 hours
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Google Drive API Libraries
        run: pip install google-api-python-client google-auth google-auth-httplib2 google-auth-oauthlib

      - name: Save service account key to file
        env:
          GDRIVE_SERVICE_KEY: ${{ secrets.GDRIVE_MARINASUITE_SERVICE_KEY }}
        run: echo "$GDRIVE_SERVICE_KEY" > service_account.json

      - name: Download MarinaSuite.zip from Google Drive
        run: |
          python3 -c "
import json
from google.oauth2 import service_account
from googleapiclient.discovery import build
import io
from googleapiclient.http import MediaIoBaseDownload

FOLDER_ID = '1FznsPANU4xNXHIlkdcJh_y-YXEdbG-do'

creds = service_account.Credentials.from_service_account_file('service_account.json')
drive = build('drive', 'v3', credentials=creds)

results = drive.files().list(
    q=f\"name='MarinaSuite.zip' and '{FOLDER_ID}' in parents and trashed=false\",
    spaces='drive',
    fields='files(id, name)'
).execute()

files = results.get('files', [])
if not files:
    raise Exception('MarinaSuite.zip not found in Google AI Studio folder')

file_id = files[0]['id']
request = drive.files().get_media(fileId=file_id)
fh = io.FileIO('marinasuite.zip', 'wb')
downloader = MediaIoBaseDownload(fh, request)

done = False
while not done:
    status, done = downloader.next_chunk()
    if status:
        print(f'Download progress: {int(status.progress() * 100)}%')
"

      - name: Unzip Project
        run: |
          rm -rf project && mkdir project
          unzip -o marinasuite.zip -d project
          cp -r project/* ./

      - name: Commit and Push Changes
        run: |
          git config user.name "aistudio-bot"
          git config user.email "bot@aistudio.com"
          git add .
          git commit -m "Auto-sync from Google AI Studio [$(date)]" || echo "No changes to commit"
          git push
